### ISSUE TITLE
doesnt create output file

### ISSUE THREAD

**Issue by fixylol** [fand/node-aviglitch#4]
it also doesnt seem to affect... anything

i used the "datamosh" command in the correct directory with the correct file and everything. it didnt seem to throw any errors, but it didnt actually change the file.

**Comment by fand** [comment]
Doesn't `datamosh` output any output file? 
Or it outputs a file without any difference from the input file?

It still works well in my environment (`npm i -g aviglitch`ed on node v7.2.1).
![2016-12-08 11 45 50](https://cloud.githubusercontent.com/assets/1403842/20995674/ec554380-bd3b-11e6-844b-9236eb33baaf.png)

If you could share the input file, it might be helpful for debugging.

**Comment by Otsomies** [comment]
Correct me if I'm wrong but it seems to me that the file has to be avi file encoded with MPEG-4 (aka. Xvid or DivX).

I used ffmpeg to convert my files: (check ffmpeg mpeg-4 guide here: https://trac.ffmpeg.org/wiki/Encode/MPEG-4)
`ffmpeg -i inputfile.mov -c:v mpeg4 -vtag xvid -q:v 2 -q:a 0  outputfile.avi
`

**Comment by fand** [comment]
ah, I tried and reproduced the bug... it doesn't output any file when the input avi was not encoded with xvid 🙀 
I'm not gonna support non-xvid files, but will fix it to show some informative messages.
Thanks!

**Comment by fand** [comment]
I just published v0.3.0, which fixes some bugs and shows more informative logs.
Please try this, and tell me what happens if it doesn't work well 🙏 
![image](https://cloud.githubusercontent.com/assets/1403842/26569297/b9eedc3a-4544-11e7-9ab2-d94e57eb4fbf.png)
